{
 "title": "SFA Drive Failures",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "dataset": "drive_stats_db", "rawSql": "select * from failed_drives;" }
   ]
  },
  {
   "title": "Drive Failures by Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "drive_stats_db",
     "rawSql": "select count(serial_number) as Count, date(timestamp) as Day from failed_drives GROUP BY Day"
    }
   ]
  },
  {
   "title": "Failure by Drive FW",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "drive_stats_db",
     "rawSql": "select count(serial_number) as Count, drive_fw_rev as \"FW Rev.\" from failed_drives GROUP BY drive_fw_rev"
    }
   ]
  },
  {
   "title": "Failure by Storage Unit",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "drive_stats_db",
     "rawSql": "select count(serial_number) as Count, storage_unit as \"Storage Unit\" from failed_drives GROUP BY storage_unit"
    }
   ]
  },
  {
   "title": "Failure by Vendor",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "drive_stats_db",
     "rawSql": "select count(serial_number) as Count, drive_vendor as Vendor from failed_drives GROUP BY drive_vendor"
    }
   ]
  },
  {
   "title": "Failure by Model",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "drive_stats_db",
     "rawSql": "select count(serial_number) as Count, drive_model as Model from failed_drives GROUP BY drive_model"
    }
   ]
  },
  {
   "title": "Failure by Drive Size",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "drive_stats_db",
     "rawSql": "select count(serial_number) as Count, drive_capacity as \"Drive Size\" from failed_drives GROUP BY \"drive_capacity\""
    }
   ]
  },
  {
   "title": "Failure by Drive Class",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "drive_stats_db",
     "rawSql": "select count(serial_number) as Count, drive_speed as \"Drive Type\" from failed_drives GROUP BY drive_speed"
    }
   ]
  }
 ]
}