{
 "title": "SFA Appliance Health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sfa_unit",
    "label": "SFA Appliance",
    "query": {
     "query": "SHOW TAG VALUES FROM sfa_controller_health WITH KEY = \"unit\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "At-A-Glance Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller Firmware Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "select last(fw_release) from sfa_controller_health where unit =~  /^$sfa_unit$/ and $timeFilter"
      }
     ]
    },
    {
     "title": "Controller Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "select last(controller_uptime_seconds) from sfa_controller_health where unit =~  /^$sfa_unit$/ and $timeFilter group by controller_index"
      }
     ]
    },
    {
     "title": "Controller Health",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "select last(health_string) from sfa_controller_health where unit =~  /^$sfa_unit$/ and $timeFilter group by controller_index"
      }
     ]
    },
    {
     "title": "Controller Local Drive Health",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "select last(system_disk_state_string) from sfa_controller_health where unit =~  /^$sfa_unit$/ and $timeFilter group by controller_index"
      }
     ]
    },
    {
     "title": "Controller % Cache Dirty",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "select last(dirty_cache_percent) from sfa_controller_health where unit =~  /^$sfa_unit$/ and $timeFilter group by controller_index"
      }
     ]
    },
    {
     "title": "Controller ICC Link Health",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "select last(icc_state_string) from sfa_controller_health where unit =~  /^$sfa_unit$/ and $timeFilter group by controller_index"
      }
     ]
    },
    {
     "title": "Enclosures with Faults",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_enclosure_type",
       "query": "select sum(enclosure_fault) from sfa_enc_health where unit =~  /^$sfa_unit$/ and time > now() - 5m GROUP BY enclosure_type"
      }
     ]
    },
    {
     "title": "Drive Health Stats",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "select last(drives_healthy), last(drives_failed), last(drives_failure_predicted), last(drives_locked) from sfa_drive_health where unit =~  /^$sfa_unit$/ and $timeFilter"
      }
     ]
    },
    {
     "title": "Stack Health",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Running Stacks",
       "query": "select sum(is_running) from sfa_vm_health where unit =~  /^$sfa_unit$/ and time > now() - 5m"
      },
      {
       "alias": "Faulted Stacks",
       "query": "select sum(fault_status) from sfa_vm_health where unit =~  /^$sfa_unit$/ and time > now() - 5m"
      }
     ]
    },
    {
     "title": "Key Temperature Data",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Ambient Temperature",
       "query": "select last(temp_celsius) from sfa_temp_health where unit =~  /^$sfa_unit$/ and time > now() - 5m  and location =~ /.*Ambient.*/"
      },
      {
       "alias": "Temps Out of Range",
       "query": "select sum(health_failure) from sfa_temp_health where unit =~  /^$sfa_unit$/ and time > now() - 5m "
      },
      {
       "alias": "Avg. ESM A Temp",
       "query": "select mean(esm_a_temps) from (select last(temp_celsius) as esm_a_temps from sfa_temp_health where location =~ /ESM_A_Exp.*/ group by location,enclosure_position)"
      },
      {
       "alias": "Avg. ESM B Temp",
       "query": "select mean(esm_b_temps) from (select last(temp_celsius) as esm_b_temps from sfa_temp_health where location =~ /ESM_B_Exp.*/ group by location,enclosure_position)"
      }
     ]
    },
    {
     "title": "Fan Health",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Fan Count",
       "query": "select count(is_present) from sfa_fan_health where unit =~  /^$sfa_unit$/ and time > now() - 5m"
      },
      {
       "alias": "Fans Faulted",
       "query": "select sum(fan_fault_true) from sfa_fan_health where unit =~  /^$sfa_unit$/ and time > now() - 5m"
      }
     ]
    },
    {
     "title": "UPS Battery Days Remaining",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Enclosure: $tag_enclosure_index",
       "query": "select last(battery_days_left) from sfa_ups_health where unit =~  /^$sfa_unit$/ and $timeFilter group by enclosure_index"
      }
     ]
    },
    {
     "title": "Expander Health",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Expander Count",
       "query": "select count(is_present) from sfa_expander_health where unit =~  /^$sfa_unit$/ and time > now() - 5m"
      },
      {
       "alias": "Faulted Expanders",
       "query": "select sum(expander_fault) from sfa_expander_health where unit =~  /^$sfa_unit$/ and time > now() - 5m"
      }
     ]
    },
    {
     "title": "Voltage Sensor Health",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Under/Over Voltage Warnings",
       "query": "select (underw+overw) from (select sum(under_volt_warn) as underw,sum(over_volt_warn) as overw from sfa_voltage_sensor_health where unit =~  /^$sfa_unit$/ and time > now() - 5m)"
      },
      {
       "alias": "Under/Over Voltage Failures",
       "query": "select (underf+overf) from (select sum(under_volt_fail) as underf,sum(over_volt_fail) as overf from sfa_voltage_sensor_health where unit =~  /^$sfa_unit$/ and time > now() - 5m)"
      }
     ]
    },
    {
     "title": "Power Supply Health",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Power Supplies",
       "query": "select count(is_present) from sfa_psu_health where unit =~  /^$sfa_unit$/ and time > now() - 5m  and location =~ /^PSU.*/"
      },
      {
       "alias": "Power Supplies No Input",
       "query": "select sum(ac_failure) from sfa_psu_health where unit =~  /^$sfa_unit$/ and time > now() - 5m  and location =~ /^PSU.*/"
      },
      {
       "alias": "Faulted Power Supplies",
       "query": "select sum(psu_fault_true) from sfa_psu_health where unit =~  /^$sfa_unit$/ and $timeFilter and location =~ /^PSU.*/"
      }
     ]
    },
    {
     "title": "UPS Battery Health",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Enclosure: $tag_enclosure_index",
       "query": "select last(health_state_string) from sfa_ups_health where unit =~  /^$sfa_unit$/ and $timeFilter group by enclosure_index"
      }
     ]
    },
    {
     "title": "Sep Health",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Sep Count",
       "query": "select count(is_present) from sfa_sep_health where unit =~  /^$sfa_unit$/ and time > now() - 5m"
      },
      {
       "alias": "Seps Faulted",
       "query": "select sum(is_failed) from sfa_sep_health where unit =~  /^$sfa_unit$/ and time > now() - 5m"
      }
     ]
    },
    {
     "title": "Pool Information",
     "type": "table",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 13 },
     "targets": [
      {
       "query": "select pool,health_string,member_count_health,member_count from sfa_pool_health where time > now() - 5m and unit =~  /^$sfa_unit$/ "
      }
     ]
    },
    {
     "title": "VD Information",
     "type": "table",
     "gridPos": { "h": 13, "w": 16, "x": 8, "y": 13 },
     "targets": [
      {
       "query": "select vd,auto_write_locked_string,verify_status_string,bad_blocks,dirty_cache_kib,home_con_rp_name,pref_home_con_rp_name from sfa_vd_health where time > now() - 5m and unit =~  /^$sfa_unit$/ "
      }
     ]
    }
   ]
  },
  {
   "title": "Performance/Environment Trend Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller Dirty Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "alias": "Bytes Controller: $tag_controller_index",
       "query": "select (dirty_cache_kib) from sfa_controller_health where unit =~  /^$sfa_unit$/ and $timeFilter group by controller_index"
      },
      {
       "alias": "% Controller: $tag_controller_index",
       "query": "select (dirty_cache_percent) from sfa_controller_health where unit =~  /^$sfa_unit$/ and $timeFilter group by controller_index"
      }
     ]
    },
    {
     "title": "VD Dirty Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "alias": "Bytes: $tag_vd",
       "query": "select (dirty_cache_kib) from sfa_vd_health where unit =~  /^$sfa_unit$/ and $timeFilter group by vd"
      }
     ]
    },
    {
     "title": "Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "alias": "$tag_location",
       "query": "select (temp_celsius) from sfa_temp_health where unit =~  /^$sfa_unit$/ and $timeFilter group by location"
      }
     ]
    },
    {
     "title": "Fan Speeds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "alias": "$tag_location",
       "query": "select (fan_speed_rpm) from sfa_fan_health where unit =~  /^$sfa_unit$/ and $timeFilter group by location"
      }
     ]
    }
   ]
  },
  {
   "title": "Health Trend Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drive Health",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "targets": [
      {
       "alias": "$col",
       "query": "select drives_failed as \"Failed Drives\", drives_failure_predicted as \"Predicted Fail Drives\", drives_locked as \"Locked Drives\" from sfa_drive_health where unit =~  /^$sfa_unit$/ and $timeFilter"
      }
     ]
    },
    {
     "title": "Power Supply Health",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "targets": [
      {
       "alias": "$col",
       "query": "select sum(ac_failure) as \"PSU AC Failure\" from sfa_psu_health where unit =~  /^$sfa_unit$/ and $timeFilter  and location =~ /^PSU.*/ group by time(5m)"
      },
      {
       "alias": "$col",
       "query": "select sum(psu_fault_true) as \"PSU Fault\" from sfa_psu_health where unit =~  /^$sfa_unit$/ and $timeFilter  and location =~ /^PSU.*/ group by time(5m)"
      }
     ]
    },
    {
     "title": "Fan Health",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "targets": [
      {
       "alias": "$col",
       "query": "select sum(fan_fault_true) as \"Fans Faulted\" from sfa_fan_health where unit =~  /^$sfa_unit$/ and $timeFilter  group by time(5m)"
      }
     ]
    },
    {
     "title": "Stack Health",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "targets": [
      {
       "alias": "$col",
       "query": "select sum(fault_status) as \"StacksFaulted\" from sfa_vm_health where unit =~  /^$sfa_unit$/ and $timeFilter  group by time(5m)"
      }
     ]
    },
    {
     "title": "Expander Health",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "targets": [
      {
       "alias": "$col",
       "query": "select expander_fault as \"Faulted Expanders\" from sfa_expander_health where unit =~  /^$sfa_unit$/ and $timeFilter"
      }
     ]
    },
    {
     "title": "Sep Health",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "targets": [
      {
       "alias": "$col",
       "query": "select sum(is_failed) as \"Seps Faulted\" from sfa_sep_health where unit =~  /^$sfa_unit$/ and $timeFilter  group by time(5m)"
      }
     ]
    },
    {
     "title": "Bad Blocks per VD",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
     "targets": [
      {
       "alias": "$tag_vd",
       "query": "select bad_blocks from sfa_vd_health where $timeFilter and unit =~  /^$sfa_unit$/ group by vd"
      }
     ]
    },
    {
     "title": "Verifies Enabled",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
     "targets": [
      {
       "alias": "$tag_vd",
       "query": "select verify_status_code as \"Verifies Enabled\" from sfa_vd_health where unit =~  /^$sfa_unit$/ and $timeFilter group by vd"
      }
     ]
    },
    {
     "title": "Pool Health",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
     "targets": [
      {
       "alias": "$tag_pool - Faults",
       "query": "select ABS(1-health_status) from sfa_pool_health where $timeFilter and unit =~  /^$sfa_unit$/ group by pool"
      }
     ]
    }
   ]
  }
 ]
}